// <auto-generated />
namespace WebsiteBanDoAnVaThucUong.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class beverage_v9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(beverage_v9));
        
        string IMigrationMetadata.Id
        {
            get { return "202411030326502_beverage_v9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
