// <auto-generated />
namespace WebsiteBanDoAnVaThucUong.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Bevergers_version2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bevergers_version2));
        
        string IMigrationMetadata.Id
        {
            get { return "202410281352120_Bevergers_version2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
