// <auto-generated />
namespace WebsiteBanDoAnVaThucUong.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Bevergers_version3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bevergers_version3));
        
        string IMigrationMetadata.Id
        {
            get { return "202410281408427_Bevergers_version3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
