// <auto-generated />
namespace WebsiteBanDoAnVaThucUong.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TMDT_addStoreProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TMDT_addStoreProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202410141002366_TMDT_addStoreProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
